import { Category } from "../schemas/category";
import { Unit } from "../schemas/unit";
import { BrandsResponse } from "../schemas/brand";
import { ProductPriceStock } from "../schemas/price";
import { Product } from "../schemas/product";
import { OfferItem } from "../schemas/offer";

export const FIXTURE_CATEGORIES: Category[] = [
  {
    id: "c9b2b5a1-7c3d-11eb-a835-0050569f41b3",
    group_uz: "Ofis jihozlari va kanselyariya",
    group_ru: "Офисная техника и канцелярия",
    group_slug_uz: "ofis-jihozlari-va-kanselyariya",
    group_slug_ru: "ofisnaya-tekhnika-i-kancelyariya",
    parent_id: "",
  },
  {
    id: "e8d3b4a2-7c3d-11eb-a835-0050569f41b4",
    group_uz: "Bog'lash mashinalari (Perforatorlar)",
    group_ru: "Переплетные машины",
    group_slug_uz: "boglash-mashinalari",
    group_slug_ru: "perepletnye-mashiny",
    parent_id: "c9b2b5a1-7c3d-11eb-a835-0050569f41b3",
    parent_name_uz: "Ofis jihozlari va kanselyariya",
    parent_name_ru: "Офисная техника и канцелярия",
  },
  {
    id: "f1a2b3c4-7c3d-11eb-a835-0050569f41b5",
    group_uz: "Kalkulyatorlar",
    group_ru: "Калькуляторы",
    group_slug_uz: "kalkulyatorlar",
    group_slug_ru: "kalkulyatory",
    parent_id: "c9b2b5a1-7c3d-11eb-a835-0050569f41b3",
    parent_name_uz: "Ofis jihozlari va kanselyariya",
    parent_name_ru: "Офисная техника и канцелярия",
  },
  {
    id: "c3d4e5f6-7c3d-11eb-a835-0050569f41b8",
    group_uz: "Qog'oz va daftarlar",
    group_ru: "Бумага и блокноты",
    group_slug_uz: "qogoz-mahsulotlari",
    group_slug_ru: "bumaga-i-bloknoty",
    parent_id: "c9b2b5a1-7c3d-11eb-a835-0050569f41b3",
    parent_name_uz: "Ofis jihozlari va kanselyariya",
    parent_name_ru: "Офисная техника и канцелярия",
  },
  {
    id: "d4e5f6g7-7c3d-11eb-a835-0050569f41b9",
    group_uz: "Yozuv qurollari",
    group_ru: "Письменные принадлежности",
    group_slug_uz: "yozuv-qurollari",
    group_slug_ru: "pismennye-prinadlezhnosti",
    parent_id: "c9b2b5a1-7c3d-11eb-a835-0050569f41b3",
    parent_name_uz: "Ofis jihozlari va kanselyariya",
    parent_name_ru: "Офисная техника и канцелярия",
  },
  {
    id: "a1b2c3d4-7c3d-11eb-a835-0050569f41b6",
    group_uz: "Elektronika",
    group_ru: "Электроника",
    group_slug_uz: "elektronika",
    group_slug_ru: "elektronika",
    parent_id: "",
  },
  {
    id: "b2c3d4e5-7c3d-11eb-a835-0050569f41b7",
    group_uz: "Smartfonlar",
    group_ru: "Смартфоны",
    group_slug_uz: "smartfonlar",
    group_slug_ru: "smartfony",
    parent_id: "a1b2c3d4-7c3d-11eb-a835-0050569f41b6",
    parent_name_uz: "Elektronika",
    parent_name_ru: "Электроника",
  },
  {
    id: "e5f6g7h8-7c3d-11eb-a835-0050569f41ba",
    group_uz: "Kompyuter aksessuarlari",
    group_ru: "Компьютерные аксессуары",
    group_slug_uz: "kompyuter-aksessuarlari",
    group_slug_ru: "kompyuternye-aksessuary",
    parent_id: "a1b2c3d4-7c3d-11eb-a835-0050569f41b6",
    parent_name_uz: "Elektronika",
    parent_name_ru: "Электроника",
  },
];

export const FIXTURE_UNITS: Unit[] = [
  { id: "7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d", name: "Штука", unit_uz: "dona", unit_ru: "шт" },
  { id: "8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e", name: "Килограмм", unit_uz: "kg", unit_ru: "кг" },
  { id: "9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f", name: "Упаковка", unit_uz: "o'ram", unit_ru: "упак" },
  { id: "0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a", name: "Пачка", unit_uz: "pachka", unit_ru: "пачка" },
];

export const FIXTURE_BRANDS: BrandsResponse = {
  brands: [
    { id: "b-deli", name: "DELI" },
    { id: "b-samsung", name: "Samsung" },
    { id: "b-logitech", name: "Logitech" },
    { id: "b-signum", name: "SIGNUM" },
    { id: "b-beshr", name: "BESHR" },
    { id: "b-hp", name: "HP" },
    { id: "b-canon", name: "Canon" },
  ],
  manufacturers: [
    { id: "m-deli", name: "Deli Group Co" },
    { id: "m-samsung", name: "Samsung Electronics" },
    { id: "m-logitech", name: "Logitech Europe" },
  ],
  countries: [
    { id: "c-cn", name: "China" },
    { id: "c-vn", name: "Vietnam" },
    { id: "c-ch", name: "Switzerland" },
    { id: "c-uz", name: "O'zbekiston" },
  ],
};

export const FIXTURE_PRICES: Record<string, ProductPriceStock> = {
  "prod-1": {
    id: "prod-1",
    stock: "InStock",
    quantity_remaining: 45,
    unit_ru: "шт",
    unit_uz: "dona",
    retail_price: 1150000,
    dealer_price: 1050000,
    wholesale_price: 980000,
    currency: "UZS",
  },
  "prod-2": {
    id: "prod-2",
    stock: "InStock",
    quantity_remaining: 180,
    unit_ru: "шт",
    unit_uz: "dona",
    retail_price: 185000,
    dealer_price: 165000,
    wholesale_price: 150000,
    currency: "UZS",
  },
  "prod-3": {
    id: "prod-3",
    stock: "InStock",
    quantity_remaining: 24,
    unit_ru: "шт",
    unit_uz: "dona",
    retail_price: 11200000,
    dealer_price: 10500000,
    wholesale_price: 9900000,
    currency: "UZS",
  },
  "prod-4": {
    id: "prod-4",
    stock: "InStock",
    quantity_remaining: 35,
    unit_ru: "шт",
    unit_uz: "dona",
    retail_price: 1450000,
    dealer_price: 1320000,
    wholesale_price: 1250000,
    currency: "UZS",
  },
  "prod-5": {
    id: "prod-5",
    stock: "InStock",
    quantity_remaining: 500,
    unit_ru: "пачка",
    unit_uz: "pachka",
    retail_price: 48000,
    dealer_price: 44000,
    wholesale_price: 41000,
    currency: "UZS",
  },
  "prod-6": {
    id: "prod-6",
    stock: "InStock",
    quantity_remaining: 320,
    unit_ru: "упак",
    unit_uz: "o'ram",
    retail_price: 35000,
    dealer_price: 30000,
    wholesale_price: 27000,
    currency: "UZS",
  },
  "prod-7": {
    id: "prod-7",
    stock: "InStock",
    quantity_remaining: 15,
    unit_ru: "шт",
    unit_uz: "dona",
    retail_price: 1420000,
    dealer_price: 1300000,
    wholesale_price: 1220000,
    currency: "UZS",
  },
  "prod-8": {
    id: "prod-8",
    stock: "InStock",
    quantity_remaining: 8,
    unit_ru: "шт",
    unit_uz: "dona",
    retail_price: 15800000,
    dealer_price: 14900000,
    wholesale_price: 14200000,
    currency: "UZS",
  },
};

export const FIXTURE_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    product_sku: "Deli E3871",
    package: "1/4",
    barcode: "6921734938718",
    brand: "DELI",
    manufacturer: "Deli Group Co",
    country: "China",
    video_url: "",
    main_picture: "https://i.ibb.co/qLcGdmjh/Deli-E3871.jpg",
    updated_at: "2026-09-28T00:00:00",
    uz: {
      unit_uz: "dona",
      category_uz: "Bog'lash mashinalari (Perforatorlar)",
      category_slug_uz: "boglash-mashinalari",
      alt_picture_uz: "Deli 3871 Plastik prujinali bog‘lash mashinasi",
      name_uz: "Plastik prujinali bog‘lash mashinasi Deli 3871",
      slug_uz: "deli-3871-boglash-mashinasi",
      title_uz: "Deli 3871 Plastik prujinali bog‘lash mashinasi",
      meta_description_uz: "Deli 3871 – 2-in-1 perforator va bog‘lovchi. Qulay dastak, aniq kesish, barqaror korpus.",
      short_description_uz: "Deli 3871 – 2-in-1 perforator va bog‘lovchi qurilma. 12 varaq teshish quvvati.",
      product_description_uz: "2-in-1 dizayni – qurilma bir vaqtning o‘zida perforator va bog‘lovchi vazifasini bajaradi.",
    },
    ru: {
      unit_ru: "шт",
      category_ru: "Переплетные машины",
      category_slug_ru: "perepletnye-mashiny",
      alt_picture_ru: "Машина для скрепления пластиковых пружин Deli 3871",
      name_ru: "Машина для скрепления пластиковых пружин Deli 3871",
      slug_ru: "deli-3871-perepletnye-mashiny",
      title_ru: "Купить переплетную машину Deli 3871 в Ташкенте",
      meta_description_ru: "Deli 3871 — устройство «2 в 1»: дырокол и переплетчик. Удобная ручка, точная пробивка.",
      short_description_ru: "Deli 3871 — устройство «2 в 1», сочетающее функции дырокола и степлера.",
      product_description_ru: "Конструкция 2-в-1 – устройство одновременно выполняет функции перфоратора и переплетчика.",
    },
    attributes: [
      { property_uz: "Brend", property_ru: "Бренд", value_uz: "DELI", value_ru: "DELI" },
      { property_uz: "Format", property_ru: "Формат", value_uz: "A4", value_ru: "A4" },
      { property_uz: "Teshish quvvati", property_ru: "Пробивная способность", value_uz: "12 varaq", value_ru: "12 листов" },
    ],
    related_products: [{ id: "prod-7", slug: "deli-3870-metal-boglash", name: "Deli E3870 Metal prujinali mashina" }],
    recommended_products: [{ id: "rec-1", slug: "plastik-prujina-12mm", name: "Plastik prujinalar A4 (100 dona)" }],
    price: FIXTURE_PRICES["prod-1"],
  },
  {
    id: "prod-2",
    product_sku: "Deli E39229",
    package: "1/40",
    barcode: "6921734939229",
    brand: "DELI",
    manufacturer: "Deli Group Co",
    country: "China",
    video_url: "",
    main_picture: "https://i.ibb.co/qLcGdmjh/Deli-E3871.jpg",
    updated_at: "2026-09-28T00:00:00",
    uz: {
      unit_uz: "dona",
      category_uz: "Kalkulyatorlar",
      category_slug_uz: "kalkulyatorlar",
      alt_picture_uz: "Deli E39229 metallik kalkulyator",
      name_uz: "Deli E39229, 14-razryadli metallik kalkulyator",
      slug_uz: "deli-e39229-metallik-kalkulyator",
      title_uz: "Deli E39229 14-razryadli stol usti kalkulyatori",
      meta_description_uz: "14 razryadli displey, metall qoplama, ikki tomonlama quvvatlanish (quyosh va batareya).",
      short_description_uz: "Buxgalteriya va ofis hisob-kitoblari uchun 14-razryadli metallik stol kalkulyatori.",
      product_description_uz: "Katta tugmachalar, aniq displey va mustahkam alyuminiy korpus.",
    },
    ru: {
      unit_ru: "шт",
      category_ru: "Калькуляторы",
      category_slug_ru: "kalkulyatory",
      alt_picture_ru: "Металлический калькулятор Deli E39229",
      name_ru: "14-разрядный металлический калькулятор Deli E39229",
      slug_ru: "deli-e39229-metallicheskij-kalkulyator",
      title_ru: "Купить настольный калькулятор Deli E39229",
      meta_description_ru: "14-разрядный дисплей, металлическая панель, двойное питание.",
      short_description_ru: "Профессиональный 14-разрядный настольный калькулятор для бухгалтерии.",
      product_description_ru: "Крупные клавиши, четкий дисплей и долговечный металлический корпус.",
    },
    attributes: [
      { property_uz: "Razryad", property_ru: "Разрядность", value_uz: "14 razryad", value_ru: "14 разрядов" },
      { property_uz: "Korpus", property_ru: "Корпус", value_uz: "Metall panel", value_ru: "Металлическая панель" },
    ],
    related_products: [{ id: "prod-2-rel", name: "Citizen 14-razryadli kalkulyator" }],
    recommended_products: [{ id: "rec-bat", name: "AA/AAA batareykalar to'plami" }, { id: "rec-note", name: "Buxgalteriya blankalari" }],
    price: FIXTURE_PRICES["prod-2"],
  },
  {
    id: "prod-3",
    product_sku: "SM-S921B",
    package: "1/10",
    barcode: "8806095300012",
    brand: "Samsung",
    manufacturer: "Samsung Electronics",
    country: "Vietnam",
    video_url: "",
    main_picture: "https://i.ibb.co/qLcGdmjh/Deli-E3871.jpg",
    updated_at: "2026-09-28T00:00:00",
    uz: {
      unit_uz: "dona",
      category_uz: "Smartfonlar",
      category_slug_uz: "smartfonlar",
      alt_picture_uz: "Samsung Galaxy S24 256GB smartfoni",
      name_uz: "Samsung Galaxy S24 8/256GB Onyx Black",
      slug_uz: "samsung-galaxy-s24-256gb",
      title_uz: "Samsung Galaxy S24 8/256GB rasmiy kafolat bilan",
      meta_description_uz: "Galaxy AI imkoniyatlari, Dynamic AMOLED 2X ekran va kuchli Exynos 2400 protsessor.",
      short_description_uz: "Sun'iy intellekt (Galaxy AI) texnologiyalari bilan jihozlangan flagman smartfon.",
      product_description_uz: "Dynamic AMOLED 2X 120Hz displey, 50MP uch kamerali tizim va ixcham alyuminiy korpus.",
    },
    ru: {
      unit_ru: "шт",
      category_ru: "Смартфоны",
      category_slug_ru: "smartfony",
      alt_picture_ru: "Смартфон Samsung Galaxy S24 256GB",
      name_ru: "Samsung Galaxy S24 8/256GB Onyx Black",
      slug_ru: "samsung-galaxy-s24-256gb",
      title_ru: "Купить Samsung Galaxy S24 256GB в Ташкенте",
      meta_description_ru: "Возможности Galaxy AI, экран Dynamic AMOLED 2X и мощный процессор.",
      short_description_ru: "Флагманский смартфон с поддержкой передовых технологий Galaxy AI.",
      product_description_ru: "Дисплей Dynamic AMOLED 2X 120Гц, тройная камера 50МП и компактный корпус.",
    },
    attributes: [
      { property_uz: "Xotira", property_ru: "Память", value_uz: "8 GB / 256 GB", value_ru: "8 ГБ / 256 ГБ" },
      { property_uz: "Ekran", property_ru: "Экран", value_uz: "6.2\" Dynamic AMOLED 2X 120Hz", value_ru: "6.2\" Dynamic AMOLED 2X 120Гц" },
    ],
    related_products: [{ id: "prod-8", name: "Samsung Galaxy S25 Ultra" }],
    recommended_products: [{ id: "rec-case", name: "Original Samsung Smart View G'ilof" }],
    price: FIXTURE_PRICES["prod-3"],
  },
  {
    id: "prod-4",
    product_sku: "LOG-MXM3S",
    package: "1/20",
    barcode: "5099206103734",
    brand: "Logitech",
    manufacturer: "Logitech Europe",
    country: "Switzerland",
    video_url: "",
    main_picture: "https://i.ibb.co/qLcGdmjh/Deli-E3871.jpg",
    updated_at: "2026-09-28T00:00:00",
    uz: {
      unit_uz: "dona",
      category_uz: "Kompyuter aksessuarlari",
      category_slug_uz: "kompyuter-aksessuarlari",
      alt_picture_uz: "Logitech MX Master 3S sichqonchasi",
      name_uz: "Logitech MX Master 3S Performance Wireless Mouse",
      slug_uz: "logitech-mx-master-3s-mouse",
      title_uz: "Logitech MX Master 3S simsiz professional sichqoncha",
      meta_description_uz: "Quiet Clicks jim bosish, 8000 DPI datchik, MagSpeed elektromagnit skroll g'ildiragi.",
      short_description_uz: "Dasturchilar va ofis mutaxassislari uchun afsonaviy ergonomik simsiz sichqoncha.",
      product_description_uz: "Har qanday sirtda (hatto oynada ham) ishlaydigan 8000 DPI sensor va 70 kunlik batareya muddati.",
    },
    ru: {
      unit_ru: "шт",
      category_ru: "Компьютерные аксессуары",
      category_slug_ru: "kompyuternye-aksessuary",
      alt_picture_ru: "Мышь Logitech MX Master 3S",
      name_ru: "Logitech MX Master 3S Performance Wireless Mouse",
      slug_ru: "logitech-mx-master-3s-mouse",
      title_ru: "Купить мышь Logitech MX Master 3S",
      meta_description_ru: "Бесшумные клики Quiet Clicks, сенсор 8000 DPI, колесо MagSpeed.",
      short_description_ru: "Легендарная эргономичная беспроводная мышь для специалистов и дизайнеров.",
      product_description_ru: "Сенсор 8000 DPI для работы на любых поверхностях, включая стекло.",
    },
    attributes: [
      { property_uz: "DPI", property_ru: "DPI", value_uz: "8000 DPI", value_ru: "8000 DPI" },
      { property_uz: "Ulanish", property_ru: "Подключение", value_uz: "Bluetooth / Logi Bolt USB", value_ru: "Bluetooth / Logi Bolt USB" },
    ],
    related_products: [],
    recommended_products: [{ id: "rec-pad", name: "Logitech Desk Mat charm gilamcha" }],
    price: FIXTURE_PRICES["prod-4"],
  },
  {
    id: "prod-5",
    product_sku: "SIG-A4-80",
    package: "5/1",
    barcode: "4780000000080",
    brand: "SIGNUM",
    manufacturer: "SIGNUM Paper",
    country: "O'zbekiston",
    video_url: "",
    main_picture: "https://i.ibb.co/qLcGdmjh/Deli-E3871.jpg",
    updated_at: "2026-09-28T00:00:00",
    uz: {
      unit_uz: "pachka",
      category_uz: "Qog'oz va daftarlar",
      category_slug_uz: "qogoz-mahsulotlari",
      alt_picture_uz: "SIGNUM A4 nusxa ko'chirish qog'ozi",
      name_uz: "SIGNUM A4 80g/m² nusxa ko'chirish qog'ozi (500 varaq)",
      slug_uz: "signum-a4-nusxa-qogoz-500",
      title_uz: "SIGNUM A4 80g qog'ozi ulgurji va chakana sotuv",
      meta_description_uz: "Ofis printerlari va nusxa ko'chirish uskunalari uchun yuqori oqlikdagi sifatli qog'oz.",
      short_description_uz: "Klassik 80g/m² zichlikdagi 500 varaqli sifatli ofis qog'ozi.",
      product_description_uz: "Tiqilib qolmaslik kafolatlangan, lazer va inkjet printerlar uchun mos.",
    },
    ru: {
      unit_ru: "пачка",
      category_ru: "Бумага и блокноты",
      category_slug_ru: "bumaga-i-bloknoty",
      alt_picture_ru: "Бумага для печати SIGNUM A4",
      name_ru: "Бумага для офисной печати SIGNUM A4 80г/м² (500 листов)",
      slug_ru: "signum-a4-bumaga-dlya-pechati",
      title_ru: "Купить бумагу SIGNUM A4 оптом и в розницу",
      meta_description_ru: "Качественная бумага высокой белизны для офисных лазерных и струйных принтеров.",
      short_description_ru: "Классическая офисная бумага плотностью 80 г/м², 500 листов в пачке.",
      product_description_ru: "Гарантия отсутствия замятий, идеальная контрастность печати.",
    },
    attributes: [
      { property_uz: "Format", property_ru: "Формат", value_uz: "A4", value_ru: "A4" },
      { property_uz: "Zichlik", property_ru: "Плотность", value_uz: "80 g/m²", value_ru: "80 г/м²" },
      { property_uz: "Varaqlar soni", property_ru: "Листов в пачке", value_uz: "500 varaq", value_ru: "500 листов" },
    ],
    related_products: [],
    recommended_products: [{ id: "rec-pen", name: "BESHR Gel ruchkalar to'plami" }],
    price: FIXTURE_PRICES["prod-5"],
  },
  {
    id: "prod-6",
    product_sku: "BSR-GP12",
    package: "1/100",
    barcode: "4780000000012",
    brand: "BESHR",
    manufacturer: "BESHR Stationeries",
    country: "O'zbekiston",
    video_url: "",
    main_picture: "https://i.ibb.co/qLcGdmjh/Deli-E3871.jpg",
    updated_at: "2026-09-28T00:00:00",
    uz: {
      unit_uz: "o'ram",
      category_uz: "Yozuv qurollari",
      category_slug_uz: "yozuv-qurollari",
      alt_picture_uz: "BESHR ko'k gel ruchkalar to'plami",
      name_uz: "BESHR Gel ruchkalar to'plami 0.5mm ko'k (12 dona)",
      slug_uz: "beshr-gel-ruchkalar-toplami-12",
      title_uz: "BESHR 0.5mm ko'k rangli gel ruchkalar to'plami",
      meta_description_uz: "Yumshoq yozuv, tez quriydigan siyoh, qulay ergonomik tutqich.",
      short_description_uz: "Ofis va o'qish uchun tezkor quriydigan 12 donali gel ruchkalar to'plami.",
      product_description_uz: "Nozik 0.5mm uchlik qog'ozda iz qoldirmaydi va silliq siljiydi.",
    },
    ru: {
      unit_ru: "упак",
      category_ru: "Письменные принадлежности",
      category_slug_ru: "pismennye-prinadlezhnosti",
      alt_picture_ru: "Набор гелевых ручек BESHR",
      name_ru: "Набор синих гелевых ручек BESHR 0.5мм (12 шт)",
      slug_ru: "beshr-nabor-gelevyh-ruchek-12",
      title_ru: "Купить набор гелевых ручек BESHR 0.5мм",
      meta_description_ru: "Мягкое скольжение, быстросохнущие чернила, эргономичный корпус.",
      short_description_ru: "Набор из 12 гелевых ручек для офиса и учебы с тонким пишущим узлом.",
      product_description_ru: "Тонкий узел 0.5 мм обеспечивает четкие и аккуратные линии без размазывания.",
    },
    attributes: [
      { property_uz: "Rangi", property_ru: "Цвет", value_uz: "Ko'k", value_ru: "Синий" },
      { property_uz: "Uchlik qalinligi", property_ru: "Толщина узла", value_uz: "0.5 mm", value_ru: "0.5 мм" },
    ],
    related_products: [],
    recommended_products: [{ id: "prod-5", name: "SIGNUM A4 nusxa ko'chirish qog'ozi" }],
    price: FIXTURE_PRICES["prod-6"],
  },
  {
    id: "prod-7",
    product_sku: "Deli E3870",
    package: "1/4",
    barcode: "6921734938701",
    brand: "DELI",
    manufacturer: "Deli Group Co",
    country: "China",
    video_url: "",
    main_picture: "https://i.ibb.co/qLcGdmjh/Deli-E3871.jpg",
    updated_at: "2026-09-28T00:00:00",
    uz: {
      unit_uz: "dona",
      category_uz: "Bog'lash mashinalari (Perforatorlar)",
      category_slug_uz: "boglash-mashinalari",
      alt_picture_uz: "Deli 3870 Metal prujinali bog‘lash mashinasi",
      name_uz: "Deli E3870 Metall prujinali professional bog‘lash mashinasi",
      slug_uz: "deli-3870-metal-boglash",
      title_uz: "Deli 3870 Metall prujinali muqovalash uskunasi",
      meta_description_uz: "3:1 qadamli metall prujinalar uchun mo'ljallangan og'ir yuklamali ofis perforatori.",
      short_description_uz: "15 varaq teshish, 130 varaq metall prujinada bog'lash sig'imi.",
      product_description_uz: "Arxiv ishlari va taqdimotlar uchun mustahkam metall prujinali yechim.",
    },
    ru: {
      unit_ru: "шт",
      category_ru: "Переплетные машины",
      category_slug_ru: "perepletnye-mashiny",
      alt_picture_ru: "Металлическая переплетная машина Deli 3870",
      name_ru: "Переплетная машина на металлическую пружину Deli 3870",
      slug_ru: "deli-3870-metal-pereplet",
      title_ru: "Купить переплетчик Deli 3870 на металлическую пружину",
      meta_description_ru: "Профессиональный переплетчик шага 3:1 для металлических пружин.",
      short_description_ru: "Перфорация 15 листов, переплет до 130 листов на металлическую пружину.",
      product_description_ru: "Идеально подходит для презентаций, календарей и архивных документов.",
    },
    attributes: [
      { property_uz: "Prujina turi", property_ru: "Тип пружины", value_uz: "Metall prujina (3:1)", value_ru: "Металлическая пружина (3:1)" },
    ],
    related_products: [{ id: "prod-1", name: "Deli E3871 Plastik prujinali mashina" }],
    recommended_products: [],
    price: FIXTURE_PRICES["prod-7"],
  },
  {
    id: "prod-8",
    product_sku: "SM-S928B",
    package: "1/10",
    barcode: "8806095300088",
    brand: "Samsung",
    manufacturer: "Samsung Electronics",
    country: "Vietnam",
    video_url: "",
    main_picture: "https://i.ibb.co/qLcGdmjh/Deli-E3871.jpg",
    updated_at: "2026-09-28T00:00:00",
    uz: {
      unit_uz: "dona",
      category_uz: "Smartfonlar",
      category_slug_uz: "smartfonlar",
      alt_picture_uz: "Samsung Galaxy S25 Ultra smartfoni",
      name_uz: "Samsung Galaxy S25 Ultra 12/512GB Titanium Gray",
      slug_uz: "samsung-galaxy-s25-ultra-512gb",
      title_uz: "Samsung Galaxy S25 Ultra 12/512GB rasmiy kafolat",
      meta_description_uz: "Titanium korpus, 200MP kamera, S-Pen ruchkasi va Snapdragon 8 Elite protsessor.",
      short_description_uz: "Top flagman: titan korpus, 200 MP kamera va o'rnatilgan S-Pen stilus.",
      product_description_uz: "Quyoshda porlamaydigan yassi Dynamic AMOLED 2X ekran va sun'iy intellektning barcha imkoniyatlari.",
    },
    ru: {
      unit_ru: "шт",
      category_ru: "Смартфоны",
      category_slug_ru: "smartfony",
      alt_picture_ru: "Смартфон Samsung Galaxy S25 Ultra",
      name_ru: "Samsung Galaxy S25 Ultra 12/512GB Titanium Gray",
      slug_ru: "samsung-galaxy-s25-ultra-512gb",
      title_ru: "Купить Samsung Galaxy S25 Ultra в Ташкенте",
      meta_description_ru: "Титановый корпус, камера 200МП, перо S-Pen и новейший процессор.",
      short_description_ru: "Флагман высшего класса с титановым корпусом и встроенным стилусом S-Pen.",
      product_description_ru: "Антибликовый экран Dynamic AMOLED 2X и максимальная производительность.",
    },
    attributes: [
      { property_uz: "Xotira", property_ru: "Память", value_uz: "12 GB / 512 GB", value_ru: "12 ГБ / 512 ГБ" },
      { property_uz: "Kamera", property_ru: "Камера", value_uz: "200 MP + 50 MP + 50 MP + 10 MP", value_ru: "200 МП + 50 МП + 50 МП + 10 МП" },
    ],
    related_products: [{ id: "prod-3", name: "Samsung Galaxy S24" }],
    recommended_products: [],
    price: FIXTURE_PRICES["prod-8"],
  },
];

export const FIXTURE_LOW_PRICE_GUARANTEE: OfferItem[] = [
  {
    offer_name: "Low price guarantee",
    Offer_start_time: "2026-10-02T16:08:34",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "f6d951a5-8dfd-11ea-81b6-50b7c370a30f",
    slug_uz: "deli-e-8014-a4-formatli-qolda-ishlaydigan-qogoz-kesish-mashinasi",
    slug_ru: "deli-e-8014-ruchnoj-rezak-formata-a4",
    name_ru: "Deli E-8014 – ручной резак формата A4",
    name_uz: "Deli E-8014 – A4 formatli qo‘lda ishlaydigan qog‘oz kesish mashinasi",
    alt_picture_uz: "A4 qog‘oz kesish mashinasi",
    alt_picture_ru: "Deli E-8014 ручной гильотинный резак A4",
    main_picture: "https://i.ibb.co/GfDNvWqb/DELI-8014.jpg",
    group_uz: "Qog'oz kesgich",
    group_ru: "Резак для бумаги",
    group_slug_uz: "qogoz-kesgich",
    group_slug_ru: "rezak-dlya-bumagi",
    brand: "DELI",
  },
  {
    "offer_name": "Low price guarantee",
    "Offer_start_time": "2026-10-02T16:08:34",
    "Offer_end_time": "2026-12-31T00:00:00",
    "id": "70ee3bb2-cd83-11ea-96bb-50b7c370a30f",
    "slug_uz": "mashina-dlya-perepleta-ssh-350l-prob-12l-f-a4-deli-e3871",
    "slug_ru": "mashina-dlya-skepleniiya-plastikovix-purjin-deli-3871",
    "name_ru": "Машина для скрепления пластиковых пружин Deli 3871",
    "name_uz": "Plastik prujinali bog‘lash mashinasi Deli 3871 ",
    "alt_picture_uz": "Deli 3871 Plastik prujinali bog‘lash mashinasi",
    "alt_picture_ru": "Машина для скрепления пластиковых пружин Deli 3871",
    "main_picture": "https://i.ibb.co/qLcGdmjh/Deli-E3871.jpg",
    "group_uz": "Ofis buyumlari",
    "group_ru": "Офисные принадлежности",
    "group_slug_uz": "ofis-buyumlari",
    "group_slug_ru": "ofisnye-prinadlezhnosti",
    "brand": "DELI"
  },
  {
    offer_name: "Low price guarantee",
    Offer_start_time: "2026-10-02T16:08:34",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "48d30aaf-1a6b-11eb-8f81-50b7c370a30f",
    slug_uz: "deli-e0358-effortless-plier-stepler",
    slug_ru: "deli-e0358-effortless-plier-stapler-chernyi-30-listov",
    name_ru: "Deli E0358 Effortless Plier Stapler",
    name_uz: "Deli E0358 Effortless Plier Stepler",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/kVQBghfK/DELI-E0358.jpg",
    group_uz: "Steplarlar",
    group_ru: "Степлеры",
    group_slug_uz: "steplarlar",
    group_slug_ru: "steplery",
    brand: "DELI",
  },
];

export const FIXTURE_NEW_PRODUCTS: OfferItem[] = [
  {
    offer_name: "New products",
    Offer_start_time: "2026-10-02T16:25:08",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "ccc62807-ca45-11eb-89de-c01885f723fa",
    slug_uz: "deli-e0386-effortless-heavy-duty-stapler-120-listov",
    slug_ru: "deli-e0386-effortless-heavy-duty-stepler-120-listov",
    name_ru: "Deli E0386 Effortless Heavy‑Duty степлер – 120 листов",
    name_uz: "Deli E0386 Effortless Heavy‑Duty stapler – 120 листов",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/8DYm9xmT/DELI-E0386.jpg",
    group_uz: "Steplarlar",
    group_ru: "Степлеры",
    group_slug_uz: "steplarlar",
    group_slug_ru: "steplery",
    brand: "DELI",
  },
  {
    offer_name: "New products",
    Offer_start_time: "2026-10-02T16:17:23",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "23af4918-d061-11eb-8d79-c01885f723fa",
    slug_uz: "schneider-slider-edge-xb-kok-sharikli-ruchka",
    slug_ru: "schneider-slider-edge-xb-chyornaya-sharikovaya-ruchka",
    name_ru: "Schneider Slider Edge XB (синий) – шариковая ручка",
    name_uz: "Schneider Slider Edge XB (ko'k) – sharikli ruchka",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/BH611QcM/152203.jpg",
    group_uz: "Sharikli ruchkalar",
    group_ru: "Шариковые ручки",
    group_slug_uz: "sharikli-ruchkalar",
    group_slug_ru: "sharikovye-ruchki",
    brand: "Schneider",
  },
  {
    offer_name: "New products",
    Offer_start_time: "2026-10-02T16:17:23",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "36466348-a5b3-11ec-974b-00155d01680c",
    slug_uz: "schneider-one-business-06-qizil-rollerball-qalam",
    slug_ru: "schneider-one-business-06-krasnyy-rollerball",
    name_ru: "Schneider One Business 06 – Красный Rollerball",
    name_uz: "Schneider One Business 06 – Qizil Rollerball Qalam",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/1fqdHG0J/183002.jpg",
    group_uz: "Rollerball ruchkalar",
    group_ru: "Роллеры ручки",
    group_slug_uz: "rollerball-ruchkalar",
    group_slug_ru: "rollery-ruchki",
    brand: "Schneider",
  },
];

export const FIXTURE_POPULAR: OfferItem[] = [
  {
    offer_name: "Popular",
    Offer_start_time: "2026-10-02T16:17:23",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "cd4b86a7-b139-11ea-8668-50b7c370a30f",
    slug_uz: "deli-e3895-eu-a3-laminator",
    slug_ru: "laminator-deli-e3895-eu-a3",
    name_ru: "Ламинатор Deli E3895-EU A3",
    name_uz: "Deli E3895-EU A3 Laminator",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/6cn6QxTH/DELI-E3895.jpg",
    group_uz: "Laminatorlar",
    group_ru: "Ламинаторы",
    group_slug_uz: "laminatorlar",
    group_slug_ru: "laminatory",
    brand: "DELI",
  },
  {
    offer_name: "Popular",
    Offer_start_time: "2026-10-02T16:17:23",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "0fa679c6-5146-11ea-8e5f-50b7c370a30f",
    slug_uz: "deli-1653-12-razryadli-stol-kalkulyatori",
    slug_ru: "deli-1653-12-razryadnyy-nastolnyy-kalkulyator",
    name_ru: "Deli 1653 – 12‑разрядный настольный калькулятор",
    name_uz: "Deli 1653 – 12‑razryadli stol kalkulyatori",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/C5FPKp9g/Deli-1653.jpg",
    group_uz: "Ish stoli kalkulyatorlari",
    group_ru: "Настольные калькуляторы",
    group_slug_uz: "ish-stoli-kalkulyatorlari",
    group_slug_ru: "nastolnye-kalkulyatory",
    brand: "DELI",
  },
  {
    offer_name: "Popular",
    Offer_start_time: "2026-10-02T16:17:23",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "e9fc0607-3551-11ec-9b58-e848b89ac546",
    slug_uz: "deli-e39034a-90x120-sm-magnitli-oq-doska",
    slug_ru: "deli-e39034a-90x120-sm-magnitno-markernaya-doska",
    name_ru: "Deli E39034A – 90×120 см магнитно‑маркерная доска",
    name_uz: "Deli E39034A – 90×120 см магнитли оқ доска",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/k20vxyDF/39034-Deli.jpg",
    group_uz: "Magnit va marker doskalari",
    group_ru: "Магнитные и маркерные доски",
    group_slug_uz: "magnit-va-marker-doskalari",
    group_slug_ru: "magnitnye-i-markernye-doski",
    brand: "DELI",
  },
];

export const FIXTURE_PROMOTIONS: OfferItem[] = [
  {
    offer_name: "Promotions",
    Offer_start_time: "2026-10-02T16:08:34",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "8764e89f-1da9-11ea-9155-d43d7e011714",
    slug_uz: "deli-e0334-keng-formatli-metal-stapler",
    slug_ru: "deli-e0334-shirokoformatnyy-metallicheskiy-stepler",
    name_ru: "Deli E0334 – широкоформатный металлический степлер",
    name_uz: "Deli E0334 – Keng formatli metal stapler",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/ym8D0Dcc/DELI-E0334.jpg",
    group_uz: "Steplarlar",
    group_ru: "Степлеры",
    group_slug_uz: "steplarlar",
    group_slug_ru: "steplery",
    brand: "DELI",
  },
  {
    offer_name: "Promotions",
    Offer_start_time: "2026-10-02T16:08:34",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "9f802e7d-d2dc-11e9-9af3-9acb931694e1",
    slug_uz: "deli-e1589-12-raqamli-kalkulyator-yashil",
    slug_ru: "deli-e1589-12-razryadnyy-kalkulyator-zelenyy",
    name_ru: "Калькулятор Deli E1589 12‑разрядный (Зеленый)",
    name_uz: "Deli E1589 12‑raqamli kalkulyator (Yashil)",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/ZzzGD7CT/DELI-1589-GN.jpg",
    group_uz: "Ish stoli kalkulyatorlari",
    group_ru: "Настольные калькуляторы",
    group_slug_uz: "ish-stoli-kalkulyatorlari",
    group_slug_ru: "nastolnye-kalkulyatory",
    brand: "DELI",
  },
  {
    offer_name: "Promotions",
    Offer_start_time: "2026-10-02T16:08:34",
    Offer_end_time: "2026-12-31T00:00:00",
    id: "4a02ff87-25ba-11f0-a25f-00155d642305",
    slug_uz: "deli-0349-comfort-touch-plier-steppler",
    slug_ru: "deli-0349-comfort-touch-plier-steppler",
    name_ru: "Deli 0349 Comfort Touch – plier‑степлер",
    name_uz: "Deli 0349 Comfort Touch – Plier степлер",
    alt_picture_uz: "",
    alt_picture_ru: "",
    main_picture: "https://i.ibb.co/Mk7RyGWc/Deli-0349.png",
    group_uz: "Steplarlar",
    group_ru: "Степлеры",
    group_slug_uz: "steplarlar",
    group_slug_ru: "steplery",
    brand: "DELI",
  },
];

export const FIXTURE_SPECIAL_OFFERS = {
  lowPrice: FIXTURE_LOW_PRICE_GUARANTEE,
  newProducts: FIXTURE_NEW_PRODUCTS,
  popular: FIXTURE_POPULAR,
  promotions: FIXTURE_PROMOTIONS,
};
